php:
  preset: laravel
<<<<<<< HEAD
=======
  version: 8
>>>>>>> 3abbe9a20101da6a35b2b6d345e4d6901f9c30cf
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
<<<<<<< HEAD
      - server.php
=======
>>>>>>> 3abbe9a20101da6a35b2b6d345e4d6901f9c30cf
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
